import Head from "next/head";
import { fetchCategories } from "../http";
import { ICategory, ICollectionResponse } from "../types";
import { AxiosResponse } from "axios";
import { GetServerSideProps, NextPage } from "next";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Coders Blog's</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to coders blog</h1>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();
  return {
    props: {
      catergories: {
        items: categories,
      },
    },
  };
};

export default Home;
